#!/usr/bin/env node
/**
 * The master document tool.
 *
 *   node master.mjs build   → assembles every content file into MASTER.md (project root)
 *   node master.mjs apply   → slices your edited MASTER.md back into the files
 *
 * Edit MASTER.md from start to finish in any editor. Each source file sits
 * between `FILE:` tags (HTML comments — invisible in markdown preview).
 * Do not remove or reorder the tags; everything between them is yours.
 * After `apply`, restart the dev server to see changes (npm run dev).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const WG = join(ROOT, 'wargame')
const MASTER = join(ROOT, 'MASTER.md')

/** Reading order: the game as the player meets it. */
const FILES = [
  'prologue.md',
  'goals.md',
  'actors/pm.md',
  'actors/sak.md',
  'actors/county.md',
  'actors/ti.md',
  'actors/hvk.md',
  'actors/aalto.md',
  'actors/startup.md',
  'phases/phase-1-sampo/briefs.md',
  'phases/phase-1-sampo/tension.md',
  'phases/phase-1-sampo/actions.md',
  'phases/phase-1-sampo/combos.md',
  'phases/phase-1-sampo/outcomes/O1.md',
  'phases/phase-1-sampo/outcomes/O2.md',
  'phases/phase-1-sampo/outcomes/O3.md',
  'phases/phase-1-sampo/outcomes/O4.md',
  'phases/phase-1-sampo/outcomes/O5.md',
  'phases/phase-2-stack/briefs.md',
  'phases/phase-2-stack/tension.md',
  'phases/phase-2-stack/actions.md',
  'phases/phase-2-stack/combos.md',
  'phases/phase-2-stack/outcomes/O1.md',
  'phases/phase-2-stack/outcomes/O2.md',
  'phases/phase-2-stack/outcomes/O3.md',
  'phases/phase-2-stack/outcomes/O4.md',
  'phases/phase-2-stack/outcomes/O5.md',
  'phases/phase-3-dividend/briefs.md',
  'phases/phase-3-dividend/tension.md',
  'phases/phase-3-dividend/actions.md',
  'phases/phase-3-dividend/combos.md',
  'phases/phase-3-dividend/outcomes/O1.md',
  'phases/phase-3-dividend/outcomes/O2.md',
  'phases/phase-3-dividend/outcomes/O3.md',
  'phases/phase-3-dividend/outcomes/O4.md',
  'phases/phase-3-dividend/outcomes/O5.md',
  'clashes.md',
  'keymetrics.md',
  'endstates.md',
  'personas/marja.md',
  'personas/eetu.md',
  'personas/endings.md',
  'epilogue.md',
  'data-indicators.md',
  'trends.md',
  'relevance.md',
  'mechanics.md',
  'causal-model.md',
  'afterword.md',
]

const TAG_OPEN = (f) => `<!-- ═══════════ FILE: ${f} ═══════════ -->`
const TAG_RE = /<!-- ═+ FILE: (.+?) ═+ -->/g

const HEADER = `<!-- MASTER DOCUMENT — generated by \`node master.mjs build\`.
     Edit anything between the FILE tags, then run \`node master.mjs apply\`
     to write your edits back into the individual files, and restart the
     dev server (npm run dev). Do not delete or reorder the FILE tags. -->

# Finland 2033 — master document

Everything the player reads, start to finish, plus the mechanics that turn
decisions into numbers. One file per section, marked by \`FILE:\` tags.

## How the variables work (cheat sheet)

**Action lines** (in the actions.md sections) carry the mechanics:
- \`- tag: A|B|H\` — the stance. A forces, B negotiates, H waits. The three
  pivotal actors' tags select the phase outcome from the combos table; the
  same tags fight the collisions in clashes.md (A beats B, B beats H, H beats A).
- \`- effects: PRO +1.0, LEG −0.7, POLL −6\` — national indices (0–10):
  RES resilience, LEG legitimacy, PRO prosperity; POLL is government approval
  (0–100, the 2031 election is scored from it).
- \`- data: pub_ai +2, trust -1.5\` — indicator deltas. Indicators
  (data-indicators.md): pub_ai, trust, youth_u, care_gap, sov_share,
  compute_mw, cap_gap, intel_cost.
- \`- flags: NAME=value; OTHER=value\` — story switches read by later phases,
  goals, key metrics and the epilogue. The main ones: MEGAPROJECT
  (full/negotiated/pilot), GUARANTEE (yes/no), SECURE_ARCH (yes/no),
  STACK (euro/us/split), CRISIS_LEG (managed/damaged), COMPACT
  (strong/thin/none), LEVY (yes/no), TALENT_PIPE, STRIKE_CARD, RETRAIN.
- \`- requires: FLAG=value (…)\` — gates an action on an earlier flag.

**Outcome files** (O1–O5 per phase) set the big picture: index effects and
POLL in the "Fires on" line, absolute indicator values in the Data block,
flag defaults under Flags, Maria/Eetu readings, and per-action hooks.

**Goals** (goals.md) use measures: \`poll >= 48\`, \`index PRO >= 7\`,
\`indicator youth_u <= 10\`, \`flag LEVY in yes\`, \`drift <= 1\` (deadlock
outcomes tolerated), \`persona EETU >= 4\`. The same grammar drives
keymetrics.md conditions.

**Epilogue** (epilogue.md) composes by scenario: Maria/Eetu sections by final
rung, Raja by STACK, Talkoot by trust+drift, Nokia by which miracle exists,
Velka by goals met and COMPACT/LEVY. \`{tokens}\` interpolate live numbers.

**Structural markers to keep intact**: headings like
\`### P1-PM-A — "Title"\`, \`# P1-O1 — Name\`, \`ACTOR vs ACTOR — Title\`,
field prefixes (\`- summary:\`, \`- effects:\`…), \`FLAG=value — Label\` lines,
\`{tokens}\`, and the \`## slug\` section names in prologue/epilogue/endings.
`

const cmd = process.argv[2]
if (cmd === 'build') {
  const parts = [HEADER]
  for (const f of FILES) {
    const path = join(WG, f)
    const body = existsSync(path) ? readFileSync(path, 'utf8').replace(/\s+$/, '') : ''
    parts.push(`\n${TAG_OPEN(f)}\n\n${body}\n`)
  }
  writeFileSync(MASTER, parts.join(''))
  console.log(`built ${MASTER} from ${FILES.length} files`)
} else if (cmd === 'apply') {
  const master = readFileSync(MASTER, 'utf8')
  const matches = [...master.matchAll(TAG_RE)]
  if (matches.length === 0) {
    console.error('No FILE tags found in MASTER.md — nothing to apply.')
    process.exit(1)
  }
  let written = 0
  for (let i = 0; i < matches.length; i++) {
    const file = matches[i][1].trim()
    const start = matches[i].index + matches[i][0].length
    const end = i + 1 < matches.length ? matches[i + 1].index : master.length
    const body = master.slice(start, end).replace(/^\s+/, '').replace(/\s+$/, '') + '\n'
    const path = join(WG, file)
    const old = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (old !== body) {
      writeFileSync(path, body)
      written++
      console.log(`updated ${file}`)
    }
  }
  console.log(`applied: ${written} file(s) changed, ${matches.length - written} unchanged`)
  console.log('Restart the dev server to see the changes (npm run dev).')
} else {
  console.log('usage: node master.mjs build | apply')
}
